### ISSUE TITLE
Invalid pesterExplorer.TestRootDirectory on opening new projet

### ISSUE THREAD

**Issue by PrzemyslawKlys** [TylerLeonhardt/vscode-pester-test-adapter#25]
So I've opened a new project, it asked me to scan things I pressed Always - and then I was greeted with invalid path + cannot debug (I guess I did it before PowerShell loaded)

![image](https://user-images.githubusercontent.com/15063294/102979208-0ae78f00-4506-11eb-9dc0-07492d3a95d5.png)

I already had:     `"pesterExplorer.testRootDirectory": "Tests"`, in my config from earlier projects. When I pressed Always `"pesterExplorer.autoDiscoverOnOpen": true` this was added which is expected. Weirdly enough Tests path exists. 

![image](https://user-images.githubusercontent.com/15063294/102979597-906b3f00-4506-11eb-8bab-4d4777a916d5.png)

Along with this error it detected some other tests - not sure where from 😂

![image](https://user-images.githubusercontent.com/15063294/102979708-bc86c000-4506-11eb-833b-db31731803c2.png)

The error appears on reopening the project again and again

**Comment by TylerLeonhardt** [comment]
What happens if you remove the `pesterExplorer.testRootDirectory` from your settings? You don't need it. It should automatically discover `Tests`

**Comment by PrzemyslawKlys** [comment]
After removal, everything works correctly. However, you can set Tests from GUI and it breaks again. Something must be wrong with this setting.

**Comment by TylerLeonhardt** [comment]
This is what happens when I code too fast... I really need to add tests. Anyway, this is fixed in 0.0.14
