### ISSUE TITLE
Add Pester 5.1 requirement

### ISSUE THREAD

**Issue by JustinGrote** [TylerLeonhardt/vscode-pester-test-adapter#31]
I was having a problem where I was only seeing the first `It` test for each item
![image](https://user-images.githubusercontent.com/15258962/104079882-e6fc9c80-51d9-11eb-9302-6d5807754c52.png)

Found I was on pester 5.0.4 and update to 5.1+ solved it, may want to add a prerequisite check.

**Comment by TylerLeonhardt** [comment]
can you give this another go with 0.0.19? I think I might have fixed it.

**Comment by JustinGrote** [comment]
It's a little tricky to retroactively do an older version of pester and not mess up my vscode, so I'll take your word for it :)
