### ISSUE TITLE
Debug Button Uses wrong ScriptPath and excludes all tests

### ISSUE THREAD

**Issue by JustinGrote** [TylerLeonhardt/vscode-pester-test-adapter#32]
The ScriptPath is missing the drive letter

This is true of both the debug codelens and the debug button in test explorer. Note `\Users` instead of `C:\users` in `ScriptPath`
![image](https://user-images.githubusercontent.com/15258962/104080839-4c9f5780-51df-11eb-81c7-794954bd2cf5.png)

**Comment by TylerLeonhardt** [comment]
Fixed in 0.0.19 that just went live

**Comment by JustinGrote** [comment]
Verified! Thank you!
