### ISSUE TITLE
Feature Request: Pester Verbosity Setting

### ISSUE THREAD

**Issue by JustinGrote** [TylerLeonhardt/vscode-pester-test-adapter#35]
When I click the run for the tests, I prefer detailed to normal output. There should be settings to mirror these settings and ideally inherit these settings if not explicity set otherwise.

![image](https://user-images.githubusercontent.com/15258962/104417347-0ec96880-552a-11eb-8c6f-072c84ba44b2.png)

**Comment by TylerLeonhardt** [comment]
Duplicate of #34 ?

**Comment by JustinGrote** [comment]
Yup. Github has been 404ing sometimes on new issue but creates the issue anyways.
