### ISSUE TITLE
The adapter should not depend on PowerShell extension preview

### ISSUE THREAD

**Issue by aguzev** [TylerLeonhardt/vscode-pester-test-adapter#37]
After installing Pester test explorer PowerShell extension preview is installed. PowerShell extension v2020.6.0+ should be the dependency.

**Comment by TylerLeonhardt** [comment]
Right now it has to because there's code in the preview extension that I depend on.

**Comment by csandfeld** [comment]
Is this still the case now that the official (non-preview) PowerShell extension has been bumped to 2021.2.2 ?

**Comment by TylerLeonhardt** [comment]
It's not. I need to update it

**Comment by TylerLeonhardt** [comment]
I just published 0.0.20 which should allow the PowerShell extension to be used. Please let me know if it works for you.

**Comment by csandfeld** [comment]
Looks good @TylerLeonhardt 👌
Thank you 😊
